baseurl = "http://humboldtux.github.io/sbcb-demo"
title = "10H 2nd Semester Blog"
canonifyurls = true
paginate = 10
languageCode = "en-us"

[author]
  name = "Chase Williams"

[[menu.main]]
  name = "ZerÎ˜es"
  url = "/zeroes"
  weight = -200
[[menu.main]]
  name = "The Water Knife"
  url = "/post/"
  weight = -180
[params]
  baseurl = "http://localhost:1313/sbcb-demo/"
